name: Docker Image

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Pylint","Test Application"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.USERNAME_DOCKER}}
          password: ${{secrets.PASSWORD_DOCKER}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gabrielsvg91/${{ github.event.repository.name }}:latest
